Fix broken example in README
When running through the simple example in the README, I get an error when trying to call ``latlng_to_cell``:

> AttributeError: module 'h3' has no attribute 'latlng_to_cell'

Looking at the python h3 API, this method is missing, but instead ``geo_to_h3`` produces an identical result to the example originally provided.